name: CI
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        platform: [Win32, x64, ARM64, '']
        build_config: [Debug, RelWithDebInfo]
        exclude:
          - os: windows-2019
            platform: ''
          - os: ubuntu-18.04
            platform: Win32
          - os: ubuntu-18.04
            platform: x64
          - os: ubuntu-18.04
            platform: ARM64
        include:
          - os: windows-2019
            platform: ARM64
            skip_tests: true

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: |
        mkdir _build
        cd _build
        cmake .. -A "${{ matrix.platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_config }}"
    - name: Build
      run: |
        cmake --build _build --config "${{ matrix.build_config }}"
    - name: Run Tests
      if: '!matrix.skip_tests'
      run: |
        cd _build
        ctest -C "${{ matrix.build_config }}"
